name: Deploy

on:
    push:
        branches: [deploy]

jobs:
    deploy:
        runs-on: self-hosted

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: yarn
            - name: Building app
              run: yarn build
            - name: Exposing build to the world
              run: rsync -a build/. /var/www/stt.zaagsys.com
